name: dpmd_gpu_v2.0
channels:
- https://conda.deepmodeling.org
dependencies:
- python>=3.6
- anaconda
- numpy
- pandas
- pip
- deepmd-kit=*=*gpu
- libdeepmd=*=*gpu
- lammps-dp
- cudatoolkit=11.3
- pip:
  - dpdata
  - ase
  - loky
  - typing_extensions
  - tqdm
  - ssh-utilities>=0.8.8
